export const COLORS = {
  primary: "#4F6EF7",
  primaryLight: "#EEF1FE",
  primaryDark: "#3A54C4",
  accent: "#FF6B35",
  accentLight: "#FFF3ED",
  success: "#22C55E",
  successLight: "#ECFDF5",
  warning: "#F59E0B",
  warningLight: "#FFFBEB",
  danger: "#EF4444",
  dangerLight: "#FEF2F2",
  purple: "#7C3AED",
  purpleLight: "#F3E8FF",
  bg: "#F8F9FC",
  card: "#FFFFFF",
  text: "#1A1D2E",
  textSecondary: "#6B7194",
  textMuted: "#9DA3C0",
  border: "#E8EBF4",
  borderLight: "#F0F2F8",
};
